### ISSUE TITLE
`lambda` usage issue

### ISSUE THREAD

**Issue by smileart** [fnando/env_vars#2]
Hey there! First of all: thank you for such a tiny, simple and incredibly useful library. It does everything I need and even more.

Regarding the issue, that's what happens:

```rb
# Let's say we have the following code. Just for the sake of example.
require 'env_vars'
require 'logger'

Config = Env::Vars.new do
  optional :log_level, string, 'WARN'

  property :logger, -> do
    logger       = Logger.new(STDOUT)
    logger.level = log_level
    logger
  end
end
```

At first glance there's, surely, nothing wrong with it. But, if we get it analysed with [`rubocop` ](https://github.com/bbatsov/rubocop) it'd [reasonably](https://github.com/bbatsov/ruby-style-guide#lambda-multi-line) recommend us to use `lambda` instead of `->` for multi-line lambdas: 

> Use the lambda method for multiline lambdas.

Fair enough. Let's do it!

```rb
# After a tiny-little bit of refactoring we'd get this
require 'env_vars'
require 'logger'

Config = Env::Vars.new do
  optional :log_level, string, 'WARN'

  property :logger, lambda do
    logger       = Logger.new(STDOUT)
    logger.level = log_level
    logger
  end
end
```

But, alas, things aren't that simple…

> `lambda': tried to create Proc object without a block (ArgumentError)

Sure! Lambda without a block got passed as a second argument of the `property` method, and our `do … end` block got passed as an implicit third block-argument of the Ruby method. Oh snap! 😯

A possible fix could be something like this (if we want to save backward compatibility, and we surely do):

```rb
    # env_vars.rb:44
    def property(name, func = nil, &block)
      value = func ? func.call : block.call

      define_singleton_method(name) { value }
    end
```

Which even passes the slightly modified tests:

```rb
  # env_vars_test.rb:177
  test "set arbitrary property with a block" do
    vars = Env::Vars.new do
      property :number { 1234 }
    end

    assert_equal 1234, vars.number
  end

  test "set arbitrary property with a lambda" do
    vars = Env::Vars.new do
      property :number, lambda { 1234 }
      property :text, -> { '1234' }
    end

    assert_equal 1234, vars.number
    assert_equal '1234', vars.text
  end
```

I'd gladly create a PR, but I 'm not sure what to do with the broken tests:

> WARN -- :       This usage of the Code Climate Test Reporter is now deprecated. Since version
>       1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
>       run the provided `codeclimate-test-reporter` binary separately to report your
>       results to Code Climate.
> 
>       More information here: https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md
> 
> rake aborted!

That's why I decided to bother you with this issue.

Maybe, there's a better solution, but the idea remains the same: it'd be nice to be able to use `lambda` method as well as `->` for backward compatibility and satisfy `rubocop` at the same time.

Thank you in advance. Really appreciate all the work you've done here. Cheers! 👍

**Comment by fnando** [comment]
Thanks for your suggestion. I just pushed a new version (v0.5.0) that implements this feature (and also dynamic properties).

**Comment by smileart** [comment]
Sorry, mate. I still have a quick question. Just tried a new version (`0.5.0`) and encountered the same issue. I see what changes you'd made in the `property` method, but they don't seem to resolve the exact case I showed above. Maybe I didn't understand something, or probably my point wasn't clear enough, but have you tried to execute the latter snippet (with `lambda`) from the first comment? Thanks in advance, anyway. Sorry for bothering you. 🙏

**Comment by fnando** [comment]
Hey Serge,

I'm still not getting it… here are the current use cases the current implementation solves:

- `property(name, callable)`
- `property(name, &block)`

The issue, I guess, is using `lambda`/`proc` with `do..end` blocks. In this case, there's nothing we can do about, right? You could either assign this to a temporary variable then pass it to the `property` method like `property(name, &var)` or using curly braces to define the lambda/proc (but that would go against rubocop linting). So the only only solution left is `property(name, &block)`:

```ruby
property :logger do
  logger = Logger.new(STDOUT)
  logger.level = log_level
  logger
end
```

I don't understand how the solution you proposed

```ruby
    # env_vars.rb:44
    def property(name, func = nil, &block)
      value = func ? func.call : block.call

      define_singleton_method(name) { value }
    end
```

would fix the `lambda`/`proc` without a block issue.

**Comment by smileart** [comment]
Hello Nando,

Sorry, man! Somehow I totally missed an option with a block. My bad. Thanks once again! I added a block instead of `lambda` and it works like a charm! Cheers!

![bitmoji](https://render.bitstrips.com/v2/cpanel/10219586-338854441_3-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by fnando** [comment]
No worries! Is still morning somewhere (that's the case for me). :)
